name       : orca
version    : 3.36.5
release    : 14
source     :
    - https://download.gnome.org/sources/orca/3.36/orca-3.36.5.tar.xz : bd88799377468b75e2571504efb3d2ca4b1f2162e0c41b88a5d51a4fee18cb5b
license    : LGPL-2.1-or-later
component  : desktop.gnome
summary    : Orca Screen Reader
description: |
    Orca is a free, open source, flexible, and extensible screen reader that provides access to the graphical desktop via user-customizable combinations of speech and/or braille.
builddeps  :
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(speech-dispatcher)
    - itstool
    - yelp-tools
rundeps    :
    - pyatspi2
    - speech-dispatcher
setup      : |
    %patch -p1 < $pkgfiles/0001-Tweak-configure.ac.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
