name       : orca
version    : 3.16.3
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/orca/3.16/orca-3.16.3.tar.xz : 540deeaa1a973cc7ccc8a463f8fcf51db51f7ccfb130bc2019ac53bf67943dc7
license    : LGPL-2.1
summary    : Orca Screen Reader
description: |
    Orca is a free, open source, flexible, and extensible screen reader that provides access to the graphical desktop via user-customizable combinations of speech and/or braille.
builddeps  :
    - itstool
    - pkgconfig(pygobject-3.0)
    - pkgconfig(atspi-2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
