name       : orca
version    : 3.20.3
release    : 3
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/orca/3.20/orca-3.20.3.tar.xz : 86a03b504f626e39247694d8d76c272a298874887a40bd044f8a535b8d689fd7
license    : LGPL-2.1
component  : desktop.gnome
summary    : Orca Screen Reader
description: |
    Orca is a free, open source, flexible, and extensible screen reader that provides access to the graphical desktop via user-customizable combinations of speech and/or braille.
builddeps  :
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(speech-dispatcher)
    - itstool
rundeps    :
    - pyatspi2
    - speech-dispatcher
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
